apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lightrag.secretName" . }}
  labels:
    {{- include "lightrag.labels" . | nindent 4 }}
type: Opaque
data:
{{- with .Values.lightragSecrets }}
  {{- if .LLM_BINDING_API_KEY }}
  LLM_BINDING_API_KEY: {{ .LLM_BINDING_API_KEY | b64enc | quote }}
  {{- end }}
  {{- if .EMBEDDING_BINDING_API_KEY }}
  EMBEDDING_BINDING_API_KEY: {{ .EMBEDDING_BINDING_API_KEY | b64enc | quote }}
  {{- end }}

  # Logic for POSTGRES_PASSWORD:
  # 1. If lightragSecrets.POSTGRES_PASSWORD is set AND existingSecret is NOT used -> Use lightragSecrets.POSTGRES_PASSWORD
  {{- if and .POSTGRES_PASSWORD (not $.Values.postgresql.auth.existingSecret) }}
  POSTGRES_PASSWORD: {{ .POSTGRES_PASSWORD | b64enc | quote }}
  # 2. Else if Postgres is enabled AND postgresql.auth.password is NOT set AND existingSecret is NOT used -> Generate random password
  {{- else if and $.Values.postgresql.enabled (not $.Values.postgresql.auth.password) (not $.Values.postgresql.auth.existingSecret) }}
  POSTGRES_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  # 3. Else if Postgres is enabled AND existingSecret is NOT used -> Use postgresql.auth.password (if set)
  {{- else if and $.Values.postgresql.enabled (not $.Values.postgresql.auth.existingSecret) }} # <--- Added 'and' here
  # Ensure postgresql.auth.password actually exists before trying to use it
  {{- if $.Values.postgresql.auth.password }}
  POSTGRES_PASSWORD: {{ $.Values.postgresql.auth.password | b64enc | quote }}
  {{- end }}
  {{- end }}
  # Note: If existingSecret IS set, this secret template deliberately does NOT add POSTGRES_PASSWORD,
  # because the password should come from the existingSecret referenced by the deployments.

  {{- if .TOKEN_SECRET }}
  TOKEN_SECRET: {{ .TOKEN_SECRET | b64enc | quote }}
  {{- end }}
  {{- if .LIGHTRAG_API_KEY }}
  LIGHTRAG_API_KEY: {{ .LIGHTRAG_API_KEY | b64enc | quote }}
  {{- end }}
  {{- if .AUTH_ACCOUNTS }}
  AUTH_ACCOUNTS: {{ .AUTH_ACCOUNTS | b64enc | quote }}
  {{- end }}
{{- end }}