apiVersion: v2
name: lightrag
description: A Helm chart for deploying the LightRAG server with WebUI and PostgreSQL backend.
type: application
version: 0.1.0 # Chart version
appVersion: "latest" # Corresponds to the LightRAG version/image tag you built